name: shop_fusion
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.1.0
  get: ^4.6.6
  cloud_firestore: ^4.15.4
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.5
  image_picker: ^1.0.7
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  flutter_svg: ^2.0.9
  carousel_slider: ^4.2.1
  flutter_riverpod: ^2.5.1
  shimmer: ^3.0.0
  intl: ^0.19.0
  url_launcher: 
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/images/

  fonts:
  - family: Lato
    fonts:
      - asset: assets/google_fonts/Lato/Lato-Black.ttf
      - asset: assets/google_fonts/Lato/Lato-BlackItalic.ttf
      - asset: assets/google_fonts/Lato/Lato-Bold.ttf
      - asset: assets/google_fonts/Lato/Lato-BoldItalic.ttf
      - asset: assets/google_fonts/Lato/Lato-Italic.ttf
      - asset: assets/google_fonts/Lato/Lato-Light.ttf
      - asset: assets/google_fonts/Lato/Lato-LightItalic.ttf
      - asset: assets/google_fonts/Lato/Lato-Regular.ttf
      - asset: assets/google_fonts/Lato/Lato-Thin.ttf
      - asset: assets/google_fonts/Lato/Lato-ThinItalic.ttf

  - family: Poppins
    fonts:
      - asset: assets/google_fonts/Poppins/Poppins-Black.ttf
      - asset: assets/google_fonts/Poppins/Poppins-BlackItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Bold.ttf
      - asset: assets/google_fonts/Poppins/Poppins-BoldItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraBold.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraBoldItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraLight.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ExtraLightItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Italic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Light.ttf
      - asset: assets/google_fonts/Poppins/Poppins-LightItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Medium.ttf
      - asset: assets/google_fonts/Poppins/Poppins-MediumItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Regular.ttf
      - asset: assets/google_fonts/Poppins/Poppins-SemiBold.ttf
      - asset: assets/google_fonts/Poppins/Poppins-SemiBoldItalic.ttf
      - asset: assets/google_fonts/Poppins/Poppins-Thin.ttf
      - asset: assets/google_fonts/Poppins/Poppins-ThinItalic.ttf